0903
Altu-Bitu/Altu-Bitu-Suu pull request #1
Opened 2021-09-05 03:10 UTC by suu3

안녕하세요! 코드리뷰 요청드립니다~
<질문>
Q1. (10994 별찍기) 2차원 배열 동적 할당 방법 보통 이렇게 쓰나요? (다른 더 좋은 방법이 있는지..!)
Q2. (10994 별찍기) 재귀에 대한 TIP이 있으신가요?
또, 저는 별찍기할 때 2차원 배열 생성해두고 나중에 한꺼번에 출력하는데 재귀함수를 돌면서 한 줄씩 출력하는 방법도 있는지 궁금해요..!
Q3. 과제는 '맞았습니다!'가 떠야지 인정이 되나요?
감사합니다 🥰🥰

2021-09-05 06:59 UTC, HyunJiLim0406 requested changes
p1
주석도 잘 작성해주셨고, 함수화도 잘해주셔서 리뷰하기 좋았습니다...!
전체적으로 흠잡을게 없는 완벽한 코드예요!!

다만, compare 함수 사용할 때 인자 다시 한 번 신경써주시구요!
p1인 이유는 1431번 때문이에요! 큰 문제는 아니지만 논리 자체가 어긋날 수도 있는 부분이라 꼭 수정해주셔야 해요!
피드백 반영해주시고 다시 리뷰어로 저 호출하시면 확인하러 오겠습니다!
아, 그리고 커밋메세지 양식 지켜주세요!

마지막으로 질문에 대한 답변 드리겠습니다.
A1. 지금 사용하신 방법이 제일 좋은 방법입니다!
A2. 사실 이 문제는 재귀 함수를 이용한다는 공통점 외에는 사람마다 코드가 천차만별인 문제예요. 재귀함수를 작성할 때 팁이라고 하면...먼저 재귀함수 종료 시점(return)이 언제 인지 잘 생각하셔야 하구요. 음...그것 말곤 없는 것 같아요! 그냥 본인이 1~2달뒤에 이 문제에 대해 거의 까먹은 상태로 그 때 작성했던 코드를 봤을 때, 이게 어떤식으로 작동하는지 한 눈에 알 수 있으면 좋은 코드라고 생각합니다. 특히 재귀 함수는 최종 결과물을 한 눈에 파악하기 어렵기도 하니까요
A3. 네! `맞았습니다!`를 받은 코드만 제출해주세요. 만약 틀렸는데 이유를 모르겠다면 코드와 함께 저희에게 질문해주시면 됩니다!

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1026.cpp
> +}
오 디버깅용으로 만드신 출력함수일까요? 잘 만드셨어요!
다만, 지금처럼 배열 2개를 동시에 출력하는게 아니라 인자로는 배열을 받고 함수에서는 배열 하나만 출력하는게 좀 더 일반성도 지니고 좋을 것 같아요!

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1026.cpp
> +}
내림차순은 compare 정의 말고 더 간단한 방법이 있었죠..!
그리고 compare 함수의 인자는 반드시 `const int &i`와 같은 형태로 하셔야 해요!

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1026.cpp
> +    sort(B.begin(), B.end());
👍

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/10994.cpp
> +    A.assign(4*(N-1) + 1, vector<char>(4*(N-1) + 1, ' ')); // 2차원 배열
이 방법으로 할당하는거 맞아요! 잘하셨어요

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/10994.cpp
> +}
👍

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/11399.cpp
> +    }
시간복잡도 O(n)으로 잘하셨어요!

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/11651.cpp
> +};
구조체 잘 정의하셨습니다!
pair container도 써보시겠어요?

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/11651.cpp
> +}
여기도 인자 수정해주세요! 코드는 너무 잘짜셨어요

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1316.cpp
> +            }
지금은 입력되는 문자열의 최대 길이가 100이라서 O(n^2)의 풀이로도 풀 수는 있어요.
하지만 매번 다른 문자가 나올 때마다 그 뒤의 모든 문자들을 검사하는건 조금 비효율적으로 보여요
굳이 문자열을 순회하지 않고 특정 알파벳이 이전에 `등장`했었는지 `여부`를 알아낼 방법은 없을까요?

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1316.cpp
> +        for( int j = 0 ; (j < word.length() - 1) && check ; j++){
그룹 단어 여부를 체크하는 이 부분을 함수로 뺀다면 check 변수가 필요없어지지 않을까요?
메인도 좀 더 짧아지구요!

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/13458.cpp
> +        }
완벽하네요!

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1431.cpp
> +            sumB += B[i]-'0';
이 부분이 중복되네요! 특정 문자열의 자릿수 합을 구하는 함수를 만드는건 어떨까요?
그리고 지금 작성하신 이 조건문은 조금 위험한 방법이에요. 물론 지금 입력 조건에선 알파벳과 숫자만 들어오겠지만, 만약 A[i]가 '+'라고 가정해볼게요. 그럼 A[i]-'0'은 -5를 리턴한답니다. 숫자 문자가 아니더라도 해당 조건문에서 true를 반환하는거예요. 어떻게 수정하면 좋을까요?

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1431.cpp
> +    }
숫자가 알파벳보다 사전순으로 작다는 문장 때문에 직접 비교문을 작성해주신 것 같아요!
이것도 정말 잘하신건데 사실 c++의 기본 비교문도 그렇답니다? `국영수`문제 풀 때 제가 사전순 비교를 어떻게 했었나요? 이 문제에서도 똑같이 적용할 수 있어요

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1946.cpp
> +            }
이 조건문은 하는 일이 없으니 없어도 되지 않을까요?

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1946.cpp
> +                standard = emp[j].interview;
👍

2021-09-05 06:59 UTC, HyunJiLim0406 commented on 0903/1946.cpp
> +        cout << total << "\n"; // 줄바꿈 안써줬다고 계속 틀려서 넘 힘들었음..
저도 이럴 때 많아요 🤣

2021-09-07 17:23 UTC, suu3 commented on 0903/1026.cpp
> +}
감사합니다! 다음부턴 그렇게 할게요 🥰

2021-09-08 11:03 UTC, HyunJiLim0406 reviewed
p3
완벽해요! 시간복잡도 면에서도 에러 핸들링면에서도 문제없는 코드예요!!
그래도 제가 드린 코멘트는 한 번 고민해주세요!
이대로 merge 하셔도 괜찮구요 더 수정해서 리뷰받고 싶으시다면 수정 후 이번처럼 리뷰어로 처 호출해주세요!
수고하셨습니다~!

8문제 다 푸셨으니 쿠폰 기록해두겠습니다~!

2021-09-08 11:03 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1316.cpp
> +        //happy
아주 잘하셨어요!
근데 alpha 배열이 전역이 아니라 이 for문안에 있다면 계속 assign으로 할당할 필요가 없어요!
꼭 필요할 때가 아니라면 전역변수는 지양하는게 좋아요!

2021-09-08 11:03 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1431.cpp
> +        }
잘 고치셨어요!

2021-09-08 12:10 UTC, merged